routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::auth();

Route::group(['middleware' => 'guest', 'namespace' => 'Auth'], function () {
    // Authentication Routes...
    Route::match(['post', 'get'], 'login', ['as' => 'login', 'uses' => 'AuthController@login']);
    Route::match(['post', 'get'], 'signup', ['as' => 'signup', 'uses' => 'AuthController@signup']);
    Route::get('oauth/login/{driver}', ['as' => 'slogin', 'uses' => 'SocialAuth@getSocialAuth']);
    Route::get('oauth/callback', ['as' => 'callback', 'uses' => 'SocialAuth@callback']);
    Route::post('password_reset', 'AuthController@password_reset')->name('password_reset');
    Route::get('password/reset/{token}', 'AuthController@reset_password')->name('reset_password');
});
Route::match(['get', 'post'], 'users/active', ['as' => 'users.active', 'uses' => 'Auth\AuthController@user_active']);
Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@logout', 'middleware' => 'auth']);
Route::get('active/{id}/{token}', ['as' => 'auth.active', 'uses' => 'Auth\AuthController@active']);
Route::get('lawyer_logout', function () {
    auth('lawyer')->logout();
    return redirect()->to('/');
});





Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    return 'Application cache cleared';
});


// b9550d85211bcd9f1861171f9c7edf5c.png
Route::get('/imageresize/medium/{photo}', function ($photo) {
    $photo_hash = md5($photo);
    $imagee = new Intervention\Image\ImageManagerStatic;
    if (!Cache::has($photo_hash)) {
        $image_encode = (string) $imagee->make(public_path($photo))
            ->resize(200, 200)
            ->encode('png', 100);
        Cache::forever($photo_hash, $image_encode);
    }
    header("Content-type: image/png");
    header('Expires: Wed, 21 Oct 2099 07:28:00 GMT');
    echo (string) Cache::get($photo_hash);
    die;
})->name('SPhone')->where('photo', '.*');


// Route::get('/testme', function() {
//     $_token = \DB::table('password_resets')->where('email', 'nebras400@gmail.com')->first();
//     if(is_null($_token)) {
//         return 'null';
//     } else {
//         dd($_token);
//     }
// });

Route::group(['namespace' => 'Site' , 'middleware' => 'fix_env'], function () {



    Route::match(['get', 'post'], 'jobs', ['as' => 'jobs', 'uses' => 'PageController@jobs']);
    Route::get('/', ['as' => 'home', 'uses' => 'IndexController@home']);
    Route::get('/home', ['uses' => 'IndexController@home']);
    Route::get('last', ['as' => 'advs.last', 'uses' => 'AdvsController@last']);
    Route::get('requests', ['as' => 'advs.requests', 'uses' => 'AdvsController@requests']);
    Route::get('country/{country}', ['as' => 'country', 'uses' => 'AdvsController@country']);
    Route::get('area/{area}', ['as' => 'area', 'uses' => 'AdvsController@area']);
    Route::get('category/{cat}/{cat_name}', ['as' => 'cats', 'uses' => 'AdvsController@cat']);
    Route::get('categories', ['as' => 'categories', 'uses' => 'AdvsController@cats']);
    Route::get('types/{name}', ['as' => 'types', 'uses' => 'AdvsController@types']);
    Route::get('search', ['as' => 'search', 'uses' => 'SearchController@search']);
    Route::get('searchdetails', ['as' => 'searchdetails', 'uses' => 'SearchController@getDetails']);
    Route::match(['get', 'post'], 'contactus', ['as' => 'contactus', 'uses' => 'PageController@contactus']);
    Route::resource('users', 'Profile');
    Route::group(['middleware' => 'auth'], function () {
        Route::any('select-subscription/{adv_id}', '\App\Http\Controllers\SubscriptionController@index')->name('select.subscription');
        Route::get('users/{username}/messages', ['as' => 'users.msgs', 'uses' => 'Profile@msgs', 'middleware' => 'auth']);
        Route::post('updatecontacts', ['as' => 'contacts', 'uses' => 'Profile@contacts']);
        Route::group(['middleware' => 'active'], function () {
            Route::get('user/shop/edit', ['as' => 'users.shop.edit', 'uses' => 'Profile@update']);
            Route::post('deladvs', ['as' => 'deladvs', 'uses' => 'AdvsController@remove']);
            Route::match(['get', 'post'], 'chat/{userid?}', ['as' => 'users.chat', 'uses' => 'ActionsController@chat']);
            Route::get('user/requests/{type}', ['as' => 'users.requests', 'uses' => 'Profile@requests']);
            Route::get('user/ads/{type?}', ['as' => 'users.advs', 'uses' => 'Profile@advs']);
            Route::get('user/followers/{id?}', ['as' => 'users.follow', 'uses' => 'Profile@follow']);
            Route::post('user/rates/{id}', ['as' => 'users.rates', 'uses' => 'Profile@rate2']);
            Route::get('user/rate/{id}/{type}', ['as' => 'users.rate', 'uses' => 'Profile@rate', 'middleware' => 'systems:rating']);
            Route::get('timeline', ['as' => 'users.timeline', 'uses' => 'Profile@timeline']);
            Route::get('claims/{type}', ['as' => 'users.claims', 'uses' => 'Profile@claims']);
            Route::get('user/joins', ['as' => 'users.joins', 'uses' => 'Profile@joins', 'middleware' => 'systems:joins']);
        });
        Route::get('documentation_form', ['as' => 'users.documentation_form', 'uses' => 'Profile@documentation_form', 'middleware' => 'auth']);
        Route::post('documentation_form', ['as' => 'users.documentation_form', 'uses' => 'Profile@documentation_form_post', 'middleware' => 'auth']);
    });
    Route::resource('advertise', 'AdvsController');
    Route::get('advertise/{id}/remove', 'AdvsController@remove')->name('advertise.remove');
    Route::get('advertise/{id}/republished', 'AdvsController@republished')->name('advertise.republished');
    Route::get('advertise/{id}/{slug}', ['as' => 'advertise.show', 'uses' => 'AdvsController@show']);
    Route::get('advertise-print/{id}', ['as' => 'advertise.print', 'uses' => 'AdvsController@print']);

    // commision
    Route::get('commision', ['as' => 'commision', 'uses' => 'PageController@commision']);
    Route::post('commision', ['as' => 'commision.store', 'uses' => 'PageController@commision_post']);
    Route::get('commision_respons', ['as' => 'commision.back', 'uses' => 'PageController@payment_callback']);
    // commision

    // Dexter
    //Route::get('commision_Dex', ['as' => 'commision_Dex', 'uses' => 'PageController@commision_Dex']);
    Route::post('commision_Dex', 'PageController@commision_post_Dex')->name('store_Dex');
    Route::get('commision_respons_DEx','PageController@payment_callback_DEx')->name('payment_callback_DEx');
    // Dexter

    Route::get('blacklist', ['as' => 'blacklist', 'uses' => 'IndexController@blacklist']);
    Route::group(['middleware' => 'active'], function () {
        Route::get('remove-image/{id}', ['as' => 'remove-image', 'uses' => 'AdvsController@remove_image']);
        Route::get('advertise/delete/{slug}/{id}', ['as' => 'advertise.destroy', 'uses' => 'AdvsController@destroy']);
        Route::match(['get', 'post'], 'report/{title}/{comment?}', ['as' => 'advertise.claims', 'uses' => 'AdvsController@claim', 'middleware' => 'auth']);
        // Route::match(['get','post'],'like/{id}/{type}',['as'=>'advertise.like','uses'=>'AdvsController@like','middleware'=>'auth']);
        Route::match(['get', 'post'], 'mediation', ['as' => 'advertise.median', 'uses' => 'AdvsController@median', 'middleware' => ['auth', 'systems:media']]);
        Route::match(['get', 'post'], 'actions/{id}/{slug}', ['as' => 'advertise.actions', 'uses' => 'AdvsController@actions', 'middleware' => 'auth']);
        Route::match(['get', 'post'], 'transfer', ['as' => 'transfer', 'uses' => 'PageController@transfer']);
        Route::get('favourites', ['as' => 'likes', 'uses' => 'ActionsController@likes', 'middleware' => 'auth']);
        Route::any('rates/{id}', ['as' => 'rates', 'uses' => 'ActionsController@rates']);
        Route::get('like/{id}/{user?}/{like?}', ['as' => 'like', 'uses' => 'ActionsController@like', 'middleware' => 'auth']);
        Route::post('bids', ['as' => 'bids', 'uses' => 'ActionsController@bids', 'middleware' => 'auth']);
        Route::post('comment', ['as' => 'comment', 'uses' => 'ActionsController@comment', 'middleware' => 'auth']);
        Route::get('list-bids', ['as' => 'list-bids', 'uses' => 'Profile@list_bids']);
        Route::get('notfications', ['as' => 'user.notfs', 'uses' => 'Profile@notfs']);
    });
    Route::get('page/{id}/{title}', ['as' => 'page', 'uses' => 'IndexController@page']);
    Route::get('joins', ['as' => 'joins', 'uses' => 'PageController@joins', 'middleware' => 'systems:joins']);
    Route::match(['get', 'post'], 'joins/request/{type}', ['as' => 'joins.request', 'uses' => 'PageController@getjoins', 'middleware' => 'active', 'middleware' => 'systems:joins']);
    Route::get('banking', ['as' => 'banking', 'uses' => 'PageController@banking']);
    Route::get('error/{type?}', ['as' => 'errors', 'uses' => 'PageController@error']);
    /* fm */
    Route::get('get-areas/{country_id}', ['as' => 'get-areas', 'uses' => 'ActionsController@getAreas']);
    Route::get('by-location/{country_id}/{area_id}', ['as' => 'get-areas', 'uses' => 'AdvsController@byLocation']);
});
Route::get('getDetails', [
    'as' => 'getDetails',
    'uses' => '\App\Http\Controllers\Admin\AdvsController@getDetails'
]);
use Carbon\Carbon ;
use App\Chat;
use App\Notfs;
use App\User;
Route::get("obaida" , function(){
    $advs = App\Advs::where('active' , 1)->where('end_date' , "<=" , Carbon::now())->get()->each(function($data){
        dd($data);
        $data->update([
            'active' => 0]);
    });
    return $advs;

});

Route::get('dayleftcron' , function (){

resources/views/admin/home.blade.php
@extends('admin.index')
@section('title') الرئيسية @stop
@section('page')
	<!-- Main content -->
	<div class="content-wrapper">

		<!-- Page header -->
		<div class="page-header">
			<div class="page-header-content">
				<div class="page-title">
					<h4><i class="icon-arrow-right6 position-right"></i> <span class="text-semibold">لوحة التحكم</span> - الرئيسية</h4>
				</div>
			</div>

			<div class="breadcrumb-line">
				<ul class="breadcrumb">
					<li><a><i class="icon-home2 position-left"></i> لوحة التحكم</a></li>
					<li class="active">الرئيسية</li>
				</ul>
			</div>
		</div>
		<!-- /page header -->


		<!-- Content area -->
		<div class="content homepage">
			<div class="row">
				<div class="col-sm-6">
					<h4 class="title">أخر الاعلانات</h4>
					<table class="table datatable-key-basic">
						<thead>
							<th>العنوان</th>
							<th>المستخدم</th>
						</thead>
						<tbody>
							@foreach($advs as $ad)
								<tr>
									<td><a href="{{route('admin.advs.show',$ad->id)}}">{{$ad->title}}</a></td>
									<td><a target="blank" href="{{route('users.show',$ad->user->username)}}">
										{{ $ad->user->username }}
									</a></td>
								</tr>
							@endforeach
						</tbody>
					</table>
					<a class="a-nav" href="{{ route('admin.advs.index',['type'=>'active']) }}">
						المزيد ...
					</a>
				</div>

				<div class="col-sm-6">
					<h4 class="title">طلبات تفعيل الاعلانات</h4>
					<table class="table datatable-key-basic">
						<thead>
							<th>العنوان</th>
							<th>المستخدم</th>
						</thead>
						<tbody>
							@foreach($not_advs as $ad)
								<tr>
									<td><a href="{{route('admin.advs.show',$ad->id)}}">{{$ad->title}}</a></td>
									<td><a target="blank" href="{{route('users.show',$ad->user->username)}}">
										{{ $ad->user->username }}
									</a></td>
								</tr>
							@endforeach
						</tbody>
					</table>
					<a class="a-nav" href="{{ route('admin.advs.index',['type'=>'not-active']) }}">
						المزيد ...
					</a>
				</div>
			</div>

			<div class="row">
				<div class="col-sm-6">
					<h4 class="title">المستخدمين الأحدث</h4>
					<table class="table datatable-key-basic">
						<thead>
							<th>الاسم</th>
							<th>تاريخ الاشتراك</th>
						</thead>
						<tbody>
							@foreach($users as $us)
								<tr>
									<td><a target="blank" href="{{route('users.show',$us->username)}}">
										{{ $us->username }}
									</a></td>
									<td>{{ $us->created_at }}</td>
								</tr>
							@endforeach
						</tbody>
					</table>
					<a class="a-nav" href="{{ route('admin.users.index',['type'=>'active']) }}">
						المزيد ...
					</a>
				</div>	

				<div class="col-sm-6">
					<h4 class="title">المستخدمين الأكثر اعلانا</h4>
					<table class="table datatable-key-basic">
						<thead>
							<th>الاسم</th>
							<th>عدد الإعلانات</th>
						</thead>
						<tbody>
							@for($i=0;$i<count($most_users) && $i<5;$i++)
								<tr>
									<td><a target="blank" href="{{route('users.show',$most_users[$i]['username'])}}">
										{{ $most_users[$i]['username'] }}
									</a></td>
									<td>{{ $most_users[$i]['count'] }}</td>
								</tr>
							@endfor
						</tbody>
					</table>
					<a class="a-nav" href="{{ route('admin.advs.index',['type'=>'active']) }}">
						المزيد ...
					</a>
				</div>				
			</div>
		</div>
		<!-- /content area -->

	</div>
	<!-- /main content -->
@stop

resources/views/admin/index.blade.php
<!DOCTYPE html>
<html lang="en" dir="rtl" lang="ar">
<head>
	@include('admin.layout.assets')
</head>

<body>

	@include('admin.layout.header')


	<!-- Page container -->
	<div class="page-container">

		<!-- Page content -->
		<div class="page-content">

			@include('admin.layout.nav')

			@yield('page')

		</div>
		<!-- /page content -->

	</div>
	@include('admin.layout.footer')
</body>
</html>

resources/views/admin/pdf.blade.php
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@700&display=swap" rel="stylesheet">
     <style type="text/css">
        body
        {
            font-family: 'Cairo', sans-serif;
            font-size: 10pt;
            direction: rtl;
        }
        table
        {
            border: 1px solid #ccc;
            border-collapse: collapse;
        }
        table th
        {
            background-color: #F7F7F7;
            color: #333;
            font-weight: bold;
        }
        table th, table td
        {
            padding: 5px;
            border: 1px solid #ccc;
        }
        @media print {
  @page { margin: 0; }
  body { margin: 1.6cm; }
}
    </style>
</head>
<body>
     <table id="tblCustomers" cellspacing="0" cellpadding="0">
        <tr>
            <th>#</th>
            <th>المعلومات</th>
        </tr>
        @foreach($data as $key=>$value)
        <tr>
            <td style="width: 300px;">{{ $key }}</td>
            <td>
                @if($key == 'تفاصيل')
                    <?php
                        $dd = explode(',',$value);
                    ?>
                    <ul>
                        @foreach($dd as $k=>$v)
                            <li>
                                {{ $v }}
                            </li>
                        @endforeach
                    </ul>
                @else
                    {!! $value !!}
                @endif
            </td>
        </tr>
        @endforeach
    </table>
    <script type="text/javascript">
        window.print();
    </script>
</body>
</html>