routes/web.php
            Notfs::create([

                'user_id'        => $adv->user_id,
                'link' =>  route('select.subscription', ['adv_id' => $adv->id]),
                'text'   => "
            	        عميلنا العزيز نفيدكم علماً بأنه تم ايقاف الاعلان الخاص بكم ورقمه $adv->id للتجديد اضغط هنا
            	        "
            ]);
            $adv->update([
                'active' => 0 ,
            ]);
            echo "adv {$adv->id} is inactive <br>" ;
        }
        else{
            echo "no item active <br>" ;
        }
    }

});

Route::get('/members', 'Site\MembersController@index')->middleware('auth')->name('select-members');
// Route::get('DSFDSFSDFSDF', function(){
//     $array = '';
//     $i = 1;
//     foreach(\App\Depts::where('parent_id' , null)->get() as $dept) {
//         $array .= drawMenuDeskTop($dept);
//         $i++;
//     }
//     dd($array);
// });



Route::group(['middleware' => ['auth', 'admin'], 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('/', ['as' => 'admin', 'uses' => 'IndexController@home']);
    Route::post('remove', ['as' => 'admin.remove', 'uses' => 'IndexController@remove']);
    Route::group(['prefix' => 'config'], function () {
        Route::match(['get', 'post'], '/', ['as' => 'admin.site_config', 'uses' => 'IndexController@site_config']);

        //Route::match(['get', 'post'], 'lawsuit_txt', ['as' => 'admin.lawsuit_txt', 'uses' => 'IndexController@lawsuit_txt']);
        Route::match(['get', 'post'], 'contacts', ['as' => 'admin.contacts', 'uses' => 'IndexController@contacts']);
        Route::match(['get', 'post'], 'contactus', ['as' => 'admin.contactus', 'uses' => 'IndexController@contactus']);
        Route::match(['get', 'post'], 'aboutus', ['as' => 'admin.aboutus', 'uses' => 'IndexController@aboutus']);
        Route::match(['get', 'post'], 'apps', ['as' => 'admin.apps', 'uses' => 'IndexController@apps']);
        Route::match(['get', 'post'], 'systems', ['as' => 'admin.systems', 'uses' => 'IndexController@systems']);
        Route::match(['get', 'post'], 'mail', ['as' => 'admin.mail', 'uses' => 'IndexController@mail']);
        Route::match(['get', 'post'], 'sms', ['as' => 'admin.sms', 'uses' => 'IndexController@sms']);
        Route::match(['get', 'post'], 'close', ['as' => 'admin.close', 'uses' => 'IndexController@close']);
    });
    Route::match(['get', 'post'], 'commissions', ['as' => 'admin.commissions', 'uses' => 'CommissionsController@index']);
    Route::match(['get', 'post'], 'advs_config/{view}', ['as' => 'admin.advs.config', 'uses' => 'IndexController@advs_config']);


    Route::get('advs/{adv}/rePublic', 'AdvsController@rePublic')->name('admin.advs.rePublic');

    Route::get('advs/{adv}/pdf', 'AdvsController@pdf')->name('admin.advs.pdf')->where('adv','[0-9]+');


    // Dexter
    // Message
    Route::get ('/Message', 'IndexController@site_Message')->name('message');
    Route::post('/Message', 'IndexController@site_Message');
    // Members
    // add new members
    Route::get ('members/new', 'MembersController@CreateNew')->name('CreateMember');
    Route::post('members/new', 'MembersController@CreateNew');

    // View members
    Route::get ('members/manage', 'MembersController@ManageMember')->name('ManageMember');
    // Edit
    Route::get ('members/edit/{id}', 'MembersController@EditMember')->name('EditMember');
    Route::post('members/edit/{id}', 'MembersController@EditMember');
    // Delete
    Route::get ('members/remove/{id}', 'MembersController@RemoveMember')->name('RemoveMember');

    // Dexter


    Route::resource('advs', 'AdvsController');
    //    Route::get('getDetails', ['as' => 'getDetails', 'uses' => 'AdvsController@getDetails']);
    Route::resource('depts', 'DeptsController');
    /*Route::resource('law_categories', 'LawCategoriesController');
    Route::resource('lawyers', 'LawyersController');
    Route::get('lawyer/requests', 'LawyersController@requests')->name('admin.lawyers.requests');
    Route::resource('lawsuits', 'LawsuitsController');
    Route::match(['get', 'post'], 'lawsuit/{id}/lawyers', 'LawsuitsController@lawyers')->name('admin.lawsuits.lawyers');
    Route::get('choose_lawyer/{id}', 'LawsuitsController@choose_lawyer')->name('choose_lawyer');
    Route::get('un_choose_lawyer/{id}', 'LawsuitsController@un_choose_lawyer')->name('un_choose_lawyer');
    Route::get('approve_lawyer/{id}', 'LawsuitsController@approve_lawyer')->name('approve_lawyer');*/
    Route::resource('props', 'PropsController');
    Route::resource('titles', 'TitlesController');
    Route::get('getProps', ['as' => 'admin.getprops', 'uses' => 'PropsController@getProps']);
    Route::get('getTitles', ['as' => 'admin.gettitles', 'uses' => 'PropsController@getTitles']);
    Route::post('delPropTypes', ['as' => 'admin.proptypes.delete', 'uses' => 'PropsController@delPropTypes']);
    Route::resource('pages', 'PagesController');
    Route::resource('operations', 'OperationsController');
    Route::resource('peroids', 'PeroidsController');
    Route::resource('country', 'CountryController');
    Route::resource('area', 'AreaController');
    Route::resource('paymethods', 'PaymethodsController');
    Route::resource('currency', 'CurrencyController');
    Route::resource('jointypes', 'JointypesController');
    Route::resource('posters', 'PostersController');
    Route::resource('sliders', 'SlidersController');
    Route::resource('users', 'UserController');
    Route::get('user/joins/requests', ['as' => 'admin.users.requests', 'uses' => 'UserController@requests']);
    Route::resource('roles', 'RolesController');
    Route::get('pays', ['as' => 'admin.pays', 'uses' => 'IndexController@pays']);
    Route::get('jobs', ['as' => 'admin.jobs', 'uses' => 'IndexController@jobs']);
    Route::get('contactus', ['as' => 'admin.contactus', 'uses' => 'IndexController@contactus']);
    Route::get('bankTransfer', 'BankTransferController@index')->name('bankTransfer');
    Route::get('claim', 'ClaimController@index')->name('admin.claim');
    //reports
    Route::get('/reports/users', 'ReportesController@users')->name('admin.reports.users');
    Route::get('/reports/advs', 'ReportesController@advs')->name('admin.reports.advs');
    Route::get('/reports/orders', 'ReportesController@orders')->name('admin.reports.orders');


    // Send Notifcation
    Route::get('/notifcation', 'NotifcationController@index')->name('admin.notifcation.index');
    Route::post('/notifcation', 'NotifcationController@store')->name('admin.notifcation.store');


    Route::get('/getDetailss', function() {
        if(request()->has('country')) {
            $lists = \App\Area::where(['country_id'=>request('country')])->get();
            return view('ajax.area')->with(['area'=>$lists])->render();
        }
        if(request()->has('area')) {
            // dd(request('area'));
            $lists = \App\Lawyer::where(['area_id'=>request('area'),'status'=>1])->get();
            return view('ajax.lawyerss')->with(['lists'=>$lists])->render();
        }
        return '';
    });

    // AreaLawyers



    // Documentation Form Catgeories
    Route::get('/documentation/category', 'DocumentationCatgeoryController@index')->name('admin.documentation.category.index');
    Route::get('/documentation/category/create', 'DocumentationCatgeoryController@create')->name('admin.documentation.category.create');
    Route::post('/documentation/category/create', 'DocumentationCatgeoryController@store')->name('admin.documentation.category.store');
    Route::get('/documentation/category/{category}/edit', 'DocumentationCatgeoryController@edit')->name('admin.documentation.category.edit')->where('category','[0-9]+');;
    Route::put('/documentation/category/{category}/update', 'DocumentationCatgeoryController@update')->name('admin.documentation.category.update')->where('category','[0-9]+');;

    // Documentation Form
    Route::get('/documentation', 'DocumentationController@index')->name('admin.documentation.index');
    Route::get('/documentation/{documentation}/show', 'DocumentationController@show')->name('admin.documentation.show')->where('documentation','[0-9]+');
    Route::get('/documentation/{documentation}/edit', 'DocumentationController@edit')->name('admin.documentation.edit')->where('documentation','[0-9]+');
    Route::put('/documentation/{documentation}/update', 'DocumentationController@update')->name('admin.documentation.update')->where('documentation','[0-9]+');
    Route::get('/documentation/{documentation}/activeted', 'DocumentationController@activeted')->name('admin.documentation.activeted')->where('documentation','[0-9]+');


    // subscriptions Form Catgeories
    Route::get('/subscriptions', 'SubscriptionController@index')->name('admin.subscription.index');
    Route::get('/subscriptions/create', 'SubscriptionController@create')->name('admin.subscription.create');
    Route::post('/subscriptions/create', 'SubscriptionController@store')->name('admin.subscription.store');
    Route::get('/subscriptions/edit/{subscription}', 'SubscriptionController@edit')->name('admin.subscription.edit');
    Route::post('/subscriptions/edit/{subscription}', 'SubscriptionController@update')->name('admin.subscription.update');
    Route::get('/subscriptions/delete/{subscription}', 'SubscriptionController@delete')->name('admin.subscription.delete');
    // Route::get('/documentation/category/create', 'DocumentationCatgeoryController@create')->name('admin.documentation.category.create');
    // Route::post('/documentation/category/create', 'DocumentationCatgeoryController@store')->name('admin.documentation.category.store');
    // Route::get('/documentation/category/{category}/edit', 'DocumentationCatgeoryController@edit')->name('admin.documentation.category.edit')->where('category','[0-9]+');;

app/Props.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Props extends Model
{
	protected $table = 'proprites';
	protected $guarded = ['id'];
	protected $hidden = ['created_at', 'updated_at'];

	public function dept()
	{
		return $this->belongsTo('App\Depts');
	}
	public function parent()
	{
		return $this->belongsTo('App\Props');
	}
	public function types()
	{
		return $this->hasMany('\App\PropTypes', 'prop_id');
	}

	public function title()
	{
		return $this->belongsTo(Titles::class, 'title_id');
	}
}

app/Http/Controllers/Admin/PropsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Depts;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Props;
use App\PropTypes;
use Validator;

class PropsController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:depts');
    }
    public function index()
    {
        return view('admin.props.index', [ 
            'props' => Props::orderBy('dept_id')->orderBy('title_id', 'asc')->orderBy('id', 'asc')->get()
        ]);
    }
    public function create()
    {
        return view('admin.props.create', ['depts' => \App\Depts::all()]);
    }
    public function store(Request $request)
    {
        $data = $request->except('_token');
        $validator = Validator::make($data, ['dept_id' => 'required']);
        if ($validator->fails()) {
            return redirect()->back()->with('error', 'يجب اختيار القسم');
        }
        $info['name'] = trim($data['name']);
        $data['parent'] ?  $info['parent'] = $data['parent'] : '';
        $info['dept_id'] = $data['dept_id'];
        $info['title_id'] = $data['title_id'] ?? null;
        $info['input'] = $data['input'];
        $info['icon'] = $data['icon'] ?? null;
        $info['main'] = $data['main'];
        $prop_id = Props::insertGetId($info);
        $i = 0;
        foreach ($data['props'] as $pr) {
            $info = [];
            if ($data['props'][$i] && $data['props'][$i] != '') {
                $info['prop_id'] = $prop_id;
                $request->has('type') ? $data['type'][$i] ? $info['parent'] = $data['type'][$i] : '' : '';
                $info['name'] = trim($data['props'][$i]);
                $image = $data['images'][$i];
                $image ? $info['image'] = uploadImage($image) : '';
                \App\PropTypes::insert($info);
            }
            $i++;
        }
        return redirect()->route('admin.props.index', ['true' => 1]);
    }
    public function edit(Request $request, $id)
    {
        $data['info'] = Props::find($id);
        if ($request->input('type') == 'main') {
            $dept = $data['info']->dept_id;
            $main = Props::where('id', $id)->first()->main;
            $main ? $main = 0 : $main = 1;
            // Props::where('id','>',0)->where('dept_id',$dept)->update(['main'=>0]);
            Props::where('id', $id)->first()->update(['main' => $main]);
            return redirect()->back();
        }
        $data['props'] = Props::all();
        $data['depts'] = \App\Depts::all();
        $data['mainprops'] = \App\Props::where('dept_id', $data['info']->dept_id)->get();
        if ($data['info']->parent) {
            $data['proptypes'] = PropTypes::where('prop_id', $data['info']->parent)->get();
        } else {
            $data['propalltypes'] = PropTypes::where('prop_id', $data['info']->id)->get();
        }
        $data = (object) $data;
        return view('admin.props.edit', ['data' => $data]);
    }
    public function update(Request $request, $id)
    {
        $data = $request->except('_token');
        $info['name'] = trim($data['name']);
        $data['parent'] ?  $info['parent'] = $data['parent'] : '';
        $info['dept_id'] = $data['dept_id'];
        $info['title_id'] = $data['title_id'] ?? null;
        $info['input'] = $data['input'];
        $info['icon'] = $data['icon'] ?? null;
        $info['main'] = $data['main'];
        Props::where('id', $id)->update($info);
        $prop_id = $id;
        $i = 0;
        if (isset($data['props'])) {
            foreach ($data['props'] as $pr) {
                $info = [];
                if ($data['props'][$i] && $data['props'][$i] != '') {
                    $info['prop_id'] = $prop_id;
                    if ($request->has('type')) {
                        $data['type'][$i] ? $info['parent'] = $data['type'][$i] : '';
                    }
                    $info['name'] = trim($data['props'][$i]);
                    $image = $data['images'][$i];
                    $image ? $info['image'] = uploadImage($image) : '';
                    if ($data['ids'][$i]) {
                        \App\PropTypes::where('id', $data['ids'][$i])->update($info);
                    } else {
                        \App\PropTypes::insert($info);
                    }
                }
                $i++;
            }
        }
        return redirect()->back()->with(['true' => 1]);
    }
    public function getProps(Request $request)
    {
        if ($request->has('prop')) {
            $prop = $request->input('prop');
            $props = PropTypes::where('prop_id', $prop)->get();
            return view('ajax.props', ['props' => $props]);
        }
        $dept = $request->input('dept');
        $props = Props::where('dept_id', $dept)->get();
        return view('ajax.mainprops', ['props' => $props]);
    }

    public function getTitles()
    {
        $dept = Depts::find(request('dept'));
        $html = '';
        foreach ($dept->titles as $title) {
            $html .= "<option value='{$title->id}'>{$title->name}</option>";
        }
        return $html;
    }
    public function delPropTypes(Request $request)
    {
        $id = $request->input('id');
        \App\PropTypes::where('id', $id)->delete();
        return 1;
    }
}

resources/views/admin/props/create.blade.php
@extends('admin.index')
@section('title') اضافة خاصية @stop
@section('page')
@push('assets')
	<link rel="stylesheet" href="{{ url('iconpicker/fontawesome-iconpicker.min.css') }}">
@endpush
<!-- Main content -->
<div class="content-wrapper">

	<!-- Page header -->
	<div class="page-header">
		<div class="page-header-content">
			<div class="page-title">
				<h4><i class="icon-arrow-right6 position-right"></i> <span class="text-semibold">الخصائص</span> - اضافة
					خاصية</h4>
			</div>
		</div>

		<div class="breadcrumb-line">
			<ul class="breadcrumb">
				<li><a href="{{route('admin.props.index')}}">الخصائص</a></li>
				<li>اضافة خاصية</li>
			</ul>
		</div>
	</div>
	<!-- /page header -->


	<!-- Content area -->
	<div class="content">

		<!-- Input group addons -->
		<div class="panel panel-flat table-responsive">
			<div class="panel-body">
				<form action="{{ route('admin.props.store') }}" class="form-horizontal" method="post"
					enctype="multipart/form-data" files>
					@if(Session::has('error'))
					<div class="alert alert-warning">{{Session::get('error')}}</div>
					@elseif(Session::has('true'))
					<div class="alert alert-success">تم التعديل بنجاح</div>
					@endif
					<fieldset class="content-group">
						<legend class="text-bold">الخاصية</legend>

						<div class="form-group">
							<label class="control-label col-lg-2">اسم الخاصية</label>
							<div class="col-lg-10">
								<div class="input-group">

									<input type="text" required class="form-control" name="name">
								</div>
							</div>
						</div>

						<div class="form-group">
							<label class="control-label col-lg-2">الايقونة</label>
							<div class="col-lg-10">
								<div class="input-group">
									<input name="icon" class="fafa-icon form-control" required>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label class="control-label col-lg-2">نوع الخاصية</label>
							<div class="col-lg-10">
								<div class="input-group">
									<select name="main" id="" class="form-control">
										<option value="0">اختيارى</option>
										<option value="1">رئيسى</option>
									</select>
								</div>
							</div>
						</div>
						
						<div class="form-group">
							<label class="control-label col-lg-2">القسم</label>
							<div class="col-lg-10">
								<div class="input-group">

									<select required class="form-control" name="dept_id" data-live-search="true"
										id="dept_titles" data-action="{{route('admin.gettitles')}}">
										<option disabled selected>اختر القسم</option>
										@foreach($depts as $d)
										<option value="{{$d->id}}">{{$d->name}}</option>
										@endforeach
									</select>
								</div>
							</div>
						</div>
						<input type="hidden" name="parent" value="0">
						<div class="form-group">
							<label class="control-label col-lg-2">نوع الخاصية</label>
							<div class="col-lg-10">
								<div class="input-group">

									<select class="norselect form-control" name="title_id">
				
									</select>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label class="control-label col-lg-2">طريقة العرض</label>
							<div class="col-lg-10">
								<div class="input-group">

									<select class="form-control" name="input">
										<option value="select">اختيارى (select)</option>
										<option value="input">مُدخل (input)</option>
									</select>
								</div>
							</div>
						</div>


						<div class="propContent">
							<div class="form-group myprops">
								<label class="control-label col-lg-2">انواع الخاصية</label>
								<div class="col-lg-10">
									<div class="input-group">
										<div class="row">
											<div class="col-sm-6">
												<input type="text" name="props[]" class="form-control">
											</div>
											<div class="col-sm-5">
												<input type="file" name="images[]">
											</div>
											<div class="col-sm-1">
												<span class="btn btn-danger fa fa-trash"></span>
											</div>
										</div>
									</div>
									<div class="other-props"></div>
								</div>
							</div>

							<a class="btn btn-danger add-other-props">
								+ اضافة نوع اخر
							</a>
						</div>
						{{ csrf_field() }}
					</fieldset>

					<div class="text-right">
						<button type="submit" class="btn btn-primary">حفظ<i
								class="icon-arrow-left13 position-right"></i></button>
					</div>
				</form>
			</div>
		</div>
		<!-- /input group addons -->

	</div>
	<!-- /content area -->

</div>
<!-- /content wrapper -->
@stop

@push('scripts')
	<script src="{{ url('iconpicker/fontawesome-iconpicker.min.js') }}"></script>
	<script>
		$('.fafa-icon').iconpicker();
	</script>
@endpush

resources/views/admin/props/index.blade.php
@extends('admin.index')
@section('title') الخصائص @stop
@section('page')
	<!-- Main content -->
		<div class="content-wrapper">

			<!-- Page header -->
			<div class="page-header">
				<div class="page-header-content">
					<div class="page-title">
						<h4><i class="icon-arrow-right6 position-right"></i> <span class="text-semibold">اعدادات التطبيق</span> - الخصائص</h4>
					</div>

				</div>

				<div class="breadcrumb-line">
					<ul class="breadcrumb">
						<li><a><i class="icon-home2 position-left"></i> اعدادات التطبيق</a></li>
						<li><a href="{{route('admin.props.index')}}">الخصائص</a></li>
					</ul>
				</div>
			</div>
			<!-- /page header -->

			@if(Session::has('true'))
			<div class="alert alert-success">تم الاضافة بنجاح</div>
			@endif
			<!-- Content area -->
			<div class="content">
				<!-- Basic initialization -->
				<div class="panel panel-flat table-responsive">
					<br />
					<center>
						<a href="{{route('admin.props.create')}}" class="btn btn-primary">
							اضافة خاصية جديدة
						</a>
						<a href="{{route('admin.titles.create')}}" class="btn btn-success">
							اضافة عنوان خصائص
						</a>
					</center>
					<table class="table datatable-key-basic normal-table">
						<thead>
							<tr>
								<th>#</th>
								<th>الأيقونة</th>
								<th>الاسم</th>
								<th>العنوان</th>
								<th>النوع</th>
								<th>تعديل</th>
								<th>حذف</th>
							</tr>
						</thead>
						<tbody>
							<?php $i=1; $thisdept=''; ?>
							@foreach($props as $info)
							@if($info->dept_id != $thisdept) 
							<tr>
								<th style="text-align: center; font-size: 17px; font-weight: bold; background: #26A69A; color:#fff;" colspan="7">{{ \App\Depts::find($info->dept_id)->name }}</th>
							</tr>
							@endif
							<tr>
								<td>{{ $i++ }}</td>
								<td><i class="fa {{ $info->icon }}"></i></td>
								<td>{{ $info->name }}</td>
								<td>
									@if($info->title)
									{{ $info->title->name}}
										<a href="{{ route('admin.titles.edit' , $info->title->id) }}">
											<i class="fa fa-pencil"></i>
										</a>
									@endif
								</td>
								<td>{{ $info->main ? "رئيسى" : "اختياري" }}</td>
								<!-- <td><a class="btn @if($info->main) btn-success @endif fa fa-home" href="{{route('admin.props.edit',$info->id)}}?type=main"></a></td> -->
								<td><a class="btn btn-primary fa fa-pencil" href="{{route('admin.props.edit',$info->id)}}"></a></td>
								<td>
									<a class="btn btn-danger fa fa-remove" data-table='proprites' data-id='{{$info->id}}'></a>
								</td>
							</tr>
							<?php $thisdept=$info->dept_id; ?>
							@endforeach
						</tbody>
					</table>
				</div>
				<!-- /basic initialization -->
			</div>
			<!-- /content area -->

		</div>
		<!-- /main content -->
@stop