routes/web.php
            Notfs::create([

                'user_id'        => $adv->user_id,
                'link' =>  route('select.subscription', ['adv_id' => $adv->id]),
                'text'   => "
            	        عميلنا العزيز نفيدكم علماً بأنه تم ايقاف الاعلان الخاص بكم ورقمه $adv->id للتجديد اضغط هنا
            	        "
            ]);
            $adv->update([
                'active' => 0 ,
            ]);
            echo "adv {$adv->id} is inactive <br>" ;
        }
        else{
            echo "no item active <br>" ;
        }
    }

});

Route::get('/members', 'Site\MembersController@index')->middleware('auth')->name('select-members');
// Route::get('DSFDSFSDFSDF', function(){
//     $array = '';
//     $i = 1;
//     foreach(\App\Depts::where('parent_id' , null)->get() as $dept) {
//         $array .= drawMenuDeskTop($dept);
//         $i++;
//     }
//     dd($array);
// });



Route::group(['middleware' => ['auth', 'admin'], 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('/', ['as' => 'admin', 'uses' => 'IndexController@home']);
    Route::post('remove', ['as' => 'admin.remove', 'uses' => 'IndexController@remove']);
    Route::group(['prefix' => 'config'], function () {
        Route::match(['get', 'post'], '/', ['as' => 'admin.site_config', 'uses' => 'IndexController@site_config']);

        //Route::match(['get', 'post'], 'lawsuit_txt', ['as' => 'admin.lawsuit_txt', 'uses' => 'IndexController@lawsuit_txt']);
        Route::match(['get', 'post'], 'contacts', ['as' => 'admin.contacts', 'uses' => 'IndexController@contacts']);
        Route::match(['get', 'post'], 'contactus', ['as' => 'admin.contactus', 'uses' => 'IndexController@contactus']);
        Route::match(['get', 'post'], 'aboutus', ['as' => 'admin.aboutus', 'uses' => 'IndexController@aboutus']);
        Route::match(['get', 'post'], 'apps', ['as' => 'admin.apps', 'uses' => 'IndexController@apps']);
        Route::match(['get', 'post'], 'systems', ['as' => 'admin.systems', 'uses' => 'IndexController@systems']);
        Route::match(['get', 'post'], 'mail', ['as' => 'admin.mail', 'uses' => 'IndexController@mail']);
        Route::match(['get', 'post'], 'sms', ['as' => 'admin.sms', 'uses' => 'IndexController@sms']);
        Route::match(['get', 'post'], 'close', ['as' => 'admin.close', 'uses' => 'IndexController@close']);
    });
    Route::match(['get', 'post'], 'commissions', ['as' => 'admin.commissions', 'uses' => 'CommissionsController@index']);
    Route::match(['get', 'post'], 'advs_config/{view}', ['as' => 'admin.advs.config', 'uses' => 'IndexController@advs_config']);


    Route::get('advs/{adv}/rePublic', 'AdvsController@rePublic')->name('admin.advs.rePublic');

    Route::get('advs/{adv}/pdf', 'AdvsController@pdf')->name('admin.advs.pdf')->where('adv','[0-9]+');


    // Dexter
    // Message
    Route::get ('/Message', 'IndexController@site_Message')->name('message');
    Route::post('/Message', 'IndexController@site_Message');
    // Members
    // add new members
    Route::get ('members/new', 'MembersController@CreateNew')->name('CreateMember');
    Route::post('members/new', 'MembersController@CreateNew');

    // View members
    Route::get ('members/manage', 'MembersController@ManageMember')->name('ManageMember');
    // Edit
    Route::get ('members/edit/{id}', 'MembersController@EditMember')->name('EditMember');
    Route::post('members/edit/{id}', 'MembersController@EditMember');
    // Delete
    Route::get ('members/remove/{id}', 'MembersController@RemoveMember')->name('RemoveMember');

    // Dexter


    Route::resource('advs', 'AdvsController');
    //    Route::get('getDetails', ['as' => 'getDetails', 'uses' => 'AdvsController@getDetails']);
    Route::resource('depts', 'DeptsController');
    /*Route::resource('law_categories', 'LawCategoriesController');
    Route::resource('lawyers', 'LawyersController');
    Route::get('lawyer/requests', 'LawyersController@requests')->name('admin.lawyers.requests');
    Route::resource('lawsuits', 'LawsuitsController');
    Route::match(['get', 'post'], 'lawsuit/{id}/lawyers', 'LawsuitsController@lawyers')->name('admin.lawsuits.lawyers');
    Route::get('choose_lawyer/{id}', 'LawsuitsController@choose_lawyer')->name('choose_lawyer');
    Route::get('un_choose_lawyer/{id}', 'LawsuitsController@un_choose_lawyer')->name('un_choose_lawyer');
    Route::get('approve_lawyer/{id}', 'LawsuitsController@approve_lawyer')->name('approve_lawyer');*/
    Route::resource('props', 'PropsController');
    Route::resource('titles', 'TitlesController');
    Route::get('getProps', ['as' => 'admin.getprops', 'uses' => 'PropsController@getProps']);
    Route::get('getTitles', ['as' => 'admin.gettitles', 'uses' => 'PropsController@getTitles']);
    Route::post('delPropTypes', ['as' => 'admin.proptypes.delete', 'uses' => 'PropsController@delPropTypes']);
    Route::resource('pages', 'PagesController');
    Route::resource('operations', 'OperationsController');
    Route::resource('peroids', 'PeroidsController');
    Route::resource('country', 'CountryController');
    Route::resource('area', 'AreaController');
    Route::resource('paymethods', 'PaymethodsController');
    Route::resource('currency', 'CurrencyController');
    Route::resource('jointypes', 'JointypesController');
    Route::resource('posters', 'PostersController');
    Route::resource('sliders', 'SlidersController');
    Route::resource('users', 'UserController');
    Route::get('user/joins/requests', ['as' => 'admin.users.requests', 'uses' => 'UserController@requests']);
    Route::resource('roles', 'RolesController');
    Route::get('pays', ['as' => 'admin.pays', 'uses' => 'IndexController@pays']);
    Route::get('jobs', ['as' => 'admin.jobs', 'uses' => 'IndexController@jobs']);
    Route::get('contactus', ['as' => 'admin.contactus', 'uses' => 'IndexController@contactus']);
    Route::get('bankTransfer', 'BankTransferController@index')->name('bankTransfer');
    Route::get('claim', 'ClaimController@index')->name('admin.claim');
    //reports
    Route::get('/reports/users', 'ReportesController@users')->name('admin.reports.users');
    Route::get('/reports/advs', 'ReportesController@advs')->name('admin.reports.advs');
    Route::get('/reports/orders', 'ReportesController@orders')->name('admin.reports.orders');


    // Send Notifcation
    Route::get('/notifcation', 'NotifcationController@index')->name('admin.notifcation.index');
    Route::post('/notifcation', 'NotifcationController@store')->name('admin.notifcation.store');


    Route::get('/getDetailss', function() {
        if(request()->has('country')) {
            $lists = \App\Area::where(['country_id'=>request('country')])->get();
            return view('ajax.area')->with(['area'=>$lists])->render();
        }
        if(request()->has('area')) {
            // dd(request('area'));
            $lists = \App\Lawyer::where(['area_id'=>request('area'),'status'=>1])->get();
            return view('ajax.lawyerss')->with(['lists'=>$lists])->render();
        }
        return '';
    });

    // AreaLawyers



    // Documentation Form Catgeories
    Route::get('/documentation/category', 'DocumentationCatgeoryController@index')->name('admin.documentation.category.index');
    Route::get('/documentation/category/create', 'DocumentationCatgeoryController@create')->name('admin.documentation.category.create');
    Route::post('/documentation/category/create', 'DocumentationCatgeoryController@store')->name('admin.documentation.category.store');
    Route::get('/documentation/category/{category}/edit', 'DocumentationCatgeoryController@edit')->name('admin.documentation.category.edit')->where('category','[0-9]+');;
    Route::put('/documentation/category/{category}/update', 'DocumentationCatgeoryController@update')->name('admin.documentation.category.update')->where('category','[0-9]+');;

    // Documentation Form
    Route::get('/documentation', 'DocumentationController@index')->name('admin.documentation.index');
    Route::get('/documentation/{documentation}/show', 'DocumentationController@show')->name('admin.documentation.show')->where('documentation','[0-9]+');
    Route::get('/documentation/{documentation}/edit', 'DocumentationController@edit')->name('admin.documentation.edit')->where('documentation','[0-9]+');
    Route::put('/documentation/{documentation}/update', 'DocumentationController@update')->name('admin.documentation.update')->where('documentation','[0-9]+');
    Route::get('/documentation/{documentation}/activeted', 'DocumentationController@activeted')->name('admin.documentation.activeted')->where('documentation','[0-9]+');


    // subscriptions Form Catgeories
    Route::get('/subscriptions', 'SubscriptionController@index')->name('admin.subscription.index');
    Route::get('/subscriptions/create', 'SubscriptionController@create')->name('admin.subscription.create');
    Route::post('/subscriptions/create', 'SubscriptionController@store')->name('admin.subscription.store');
    Route::get('/subscriptions/edit/{subscription}', 'SubscriptionController@edit')->name('admin.subscription.edit');
    Route::post('/subscriptions/edit/{subscription}', 'SubscriptionController@update')->name('admin.subscription.update');
    Route::get('/subscriptions/delete/{subscription}', 'SubscriptionController@delete')->name('admin.subscription.delete');
    // Route::get('/documentation/category/create', 'DocumentationCatgeoryController@create')->name('admin.documentation.category.create');
    // Route::post('/documentation/category/create', 'DocumentationCatgeoryController@store')->name('admin.documentation.category.store');
    // Route::get('/documentation/category/{category}/edit', 'DocumentationCatgeoryController@edit')->name('admin.documentation.category.edit')->where('category','[0-9]+');;

app/Http/Controllers/Admin/PaymethodsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Paymethods;

class PaymethodsController extends Controller {

    public function __construct() {
        $this->middleware('role:payments');
    }

    public function index() {
        return view('admin.paymethods.index', ['paymethods' => \App\Paymethods::all()]);
    }

    public function create() {
        return view('admin.paymethods.create');
    }

    public function store(Request $request) {
        $data = $request->except('_token');
        $image = $request->file('image');
        $image ? $data['image'] = uploadImage($image) : $data['image'] = '';
        Paymethods::insert($data);
        return redirect()->route('admin.paymethods.index', ['true' => 1]);
    }

    public function edit($id) {
        return view('admin.paymethods.edit', ['info' => Paymethods::find($id)]);
    }

    public function update(Request $request, $id) {
        $data = $request->except('_method', '_token');
        $image = $request->file('image');
        if ($image) {
            $data['image'] = uploadImage($image);
        } else {
            $data['image'] = '';
        }
        Paymethods::where('id', $id)->update($data);
        return redirect()->back()->with('true', "تم التعديل بنجاح");
    }

}

resources/views/admin/paymethods/create.blade.php
@extends('admin.index')
@section('title') اضافة نظام دفع @stop
@section('page')
<!-- Main content -->
<div class="content-wrapper">

    <!-- Page header -->
    <div class="page-header">
        <div class="page-header-content">
            <div class="page-title">
                <h4><i class="icon-arrow-right6 position-right"></i> <span class="text-semibold">أنظمة الدفع</span> - اضافة نظام دفع</h4>
            </div>
        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb">
                <li><a href="{{route('admin.paymethods.index')}}">أنظمة الدفع</a></li>
                <li>اضافة نظام دفع</li>
            </ul>
        </div>
    </div>
    <!-- /page header -->


    <!-- Content area -->
    <div class="content">

        <!-- Input group addons -->
        <div class="panel panel-flat table-responsive">
            <div class="panel-body">
                <form action="{{ route('admin.paymethods.store') }}" class="form-horizontal" method="post" enctype="multipart/form-data">
                    @if(Session::has('error'))
                    <div class="alert alert-warning">{{Session::get('error')}}</div>
                    @elseif(Session::has('true'))
                    <div class="alert alert-success">تم التعديل بنجاح</div>
                    @endif
                    <fieldset class="content-group">
                        <legend class="text-bold">نظام دفع</legend>

                        <div class="form-group">
                            <label class="control-label col-lg-2">اسم نظام دفع</label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <input type="text" required class="form-control" name="name">
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-lg-2">نوع النظام</label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <select name="type" class="form-control">
                                        @foreach(payTypes() as $key=>$pt)
                                        <option value="{{$key}}">
                                            {{$pt}}
                                        </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-lg-2">صورة دالة</label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <input type="file" id="uploadfile" name="image">
                                </div>
                            </div>
                        </div>
                        <?php
                        /*

                          <div class="form-group">
                          <label class="control-label col-lg-12">معلومات النظام</label>
                          <div class="col-lg-12">
                          <div class="input-group">
                          <textarea id="editor" name="info"></textarea>
                          </div>
                          </div>
                          </div>
                         */
                        ?>
                        <div class="form-group">
                            <label class="control-label col-lg-2">معلومات النظام</label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <input type="text" required class="form-control" value="" name="info">
                                </div>
                            </div>
                        </div>
                        {{ csrf_field() }}
                    </fieldset>

                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">حفظ<i class="icon-arrow-left13 position-right"></i></button>
                    </div>
                </form>
            </div>
        </div>
        <!-- /input group addons -->

    </div>
    <!-- /content area -->

</div>
<!-- /content wrapper -->
@stop

resources/views/admin/paymethods/edit.blade.php
@extends('admin.index')
@section('title') تعديل نظام دفع @stop
@section('page')
<!-- Main content -->
<div class="content-wrapper">

    <!-- Page header -->
    <div class="page-header">
        <div class="page-header-content">
            <div class="page-title">
                <h4><i class="icon-arrow-right6 position-right"></i> <span class="text-semibold">أنظمة الدفع</span> - تعديل نظام دفع</h4>
            </div>
        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb">
                <li><a href="{{route('admin.paymethods.index')}}">أنظمة الدفع</a></li>
                <li>تعديل نظام دفع</li>
            </ul>
        </div>
    </div>
    <!-- /page header -->


    <!-- Content area -->
    <div class="content">

        <!-- Input group addons -->
        <div class="panel panel-flat table-responsive">
            <div class="panel-body">
                <form action="{{ route('admin.paymethods.update',$info->id) }}" class="form-horizontal" method="post" enctype="multipart/form-data">
                    @if(Session::has('error'))
                    <div class="alert alert-warning">{{Session::get('error')}}</div>
                    @elseif(Session::has('true'))
                    <div class="alert alert-success">تم التعديل بنجاح</div>
                    @endif
                    {{ method_field('PUT')}}
                    <fieldset class="content-group">
                        <legend class="text-bold">نظام دفع</legend>

                        <div class="form-group">
                            <label class="control-label col-lg-2">اسم نظام دفع</label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <input type="text" required class="form-control" value="{{$info->name}}" name="name">
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-lg-2">نوع النظام</label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <select name="type" class="form-control">
                                        @foreach(payTypes() as $key=>$pt)
                                        <option value="{{$key}}" @if($key==$info->type) selected @endif >
                                                {{$pt}}
                                    </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-lg-2">صورة دالة</label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <input type="file" id="uploadfile" name="image" @if($info->image) data-file="{{url('/').$info->image}}" @endif>
                            </div>
                        </div>
                    </div>

                    <?php /*
                      <div class="form-group">
                      <label class="control-label col-lg-2">معلومات النظام</label>
                      <div class="col-lg-12">
                      <div class="input-group">
                      <input type="text" required class="form-control" value="{{$info->info}}" name="info">
                      <textarea id="_editor" class="form-control" name="info">{{$info->info}}</textarea>
                      </div>
                      </div>
                      </div>
                     */
                    ?>
                    <div class="form-group">
                        <label class="control-label col-lg-2">معلومات النظام</label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <input type="text" required class="form-control" value="{{$info->info}}" name="info">
                            </div>
                        </div>
                    </div>


                    {{ csrf_field() }}
                </fieldset>

                <div class="text-right">
                    <button type="submit" class="btn btn-primary">حفظ<i class="icon-arrow-left13 position-right"></i></button>
                </div>
            </form>
        </div>
    </div>
    <!-- /input group addons -->

</div>
<!-- /content area -->

</div>
<!-- /content wrapper -->
@stop

resources/views/admin/paymethods/index.blade.php
@extends('admin.index')
@section('title') أنظمة الدفع @stop
@section('page')
	<!-- Main content -->
		<div class="content-wrapper">

			<!-- Page header -->
			<div class="page-header">
				<div class="page-header-content">
					<div class="page-title">
						<h4><i class="icon-arrow-right6 position-right"></i> <span class="text-semibold">اعدادات التطبيق</span> - أنظمة الدفع</h4>
					</div>

				</div>

				<div class="breadcrumb-line">
					<ul class="breadcrumb">
						<li><a><i class="icon-home2 position-left"></i> اعدادات التطبيق</a></li>
						<li><a href="{{route('admin.paymethods.index')}}">أنظمة الدفع</a></li>
					</ul>
				</div>
			</div>
			<!-- /page header -->

			@if(Session::has('true'))
			<div class="alert alert-success">تم الاضافة بنجاح</div>
			@endif
			<!-- Content area -->
			<div class="content">
				<!-- Basic initialization -->
				<div class="panel panel-flat table-responsive">
					<table class="table datatable-key-basic">
						<thead>
							<tr>
								<th>#</th>
								<th>الاسم</th>
								<th>النوع</th>
								<th>تعديل</th>
								<th>حذف</th>
							</tr>
						</thead>
						<tbody>
							<?php $i=1; ?>
							@foreach($paymethods as $info)
							<tr>
								<td>{{ $i++ }}</td>
								<td>{{ $info->name }}</td>
								<td>{{ payTypes()[$info->type] }}</td>		
								<td><a class="btn btn-primary fa fa-pencil" href="{{route('admin.paymethods.edit',$info->id)}}"></a></td>
								<td>
									<a class="btn btn-danger fa fa-remove" data-table='pay_methods' data-id='{{$info->id}}'></a>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
				<!-- /basic initialization -->
			</div>
			<!-- /content area -->

		</div>
		<!-- /main content -->
@stop