routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::auth();

Route::group(['middleware' => 'guest', 'namespace' => 'Auth'], function () {
    // Authentication Routes...
    Route::match(['post', 'get'], 'login', ['as' => 'login', 'uses' => 'AuthController@login']);
    Route::match(['post', 'get'], 'signup', ['as' => 'signup', 'uses' => 'AuthController@signup']);
    Route::get('oauth/login/{driver}', ['as' => 'slogin', 'uses' => 'SocialAuth@getSocialAuth']);
    Route::get('oauth/callback', ['as' => 'callback', 'uses' => 'SocialAuth@callback']);
    Route::post('password_reset', 'AuthController@password_reset')->name('password_reset');
    Route::get('password/reset/{token}', 'AuthController@reset_password')->name('reset_password');
});
Route::match(['get', 'post'], 'users/active', ['as' => 'users.active', 'uses' => 'Auth\AuthController@user_active']);
Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@logout', 'middleware' => 'auth']);
Route::get('active/{id}/{token}', ['as' => 'auth.active', 'uses' => 'Auth\AuthController@active']);
Route::get('lawyer_logout', function () {
    auth('lawyer')->logout();
    return redirect()->to('/');
});





Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    return 'Application cache cleared';
});


// b9550d85211bcd9f1861171f9c7edf5c.png
Route::get('/imageresize/medium/{photo}', function ($photo) {
    $photo_hash = md5($photo);
    $imagee = new Intervention\Image\ImageManagerStatic;
    if (!Cache::has($photo_hash)) {
        $image_encode = (string) $imagee->make(public_path($photo))
            ->resize(200, 200)
            ->encode('png', 100);
        Cache::forever($photo_hash, $image_encode);
    }
    header("Content-type: image/png");
    header('Expires: Wed, 21 Oct 2099 07:28:00 GMT');
    echo (string) Cache::get($photo_hash);
    die;
})->name('SPhone')->where('photo', '.*');


// Route::get('/testme', function() {
//     $_token = \DB::table('password_resets')->where('email', 'nebras400@gmail.com')->first();
//     if(is_null($_token)) {
//         return 'null';
//     } else {
//         dd($_token);
//     }
// });

Route::group(['namespace' => 'Site' , 'middleware' => 'fix_env'], function () {



    Route::match(['get', 'post'], 'jobs', ['as' => 'jobs', 'uses' => 'PageController@jobs']);
    Route::get('/', ['as' => 'home', 'uses' => 'IndexController@home']);
    Route::get('/home', ['uses' => 'IndexController@home']);
    Route::get('last', ['as' => 'advs.last', 'uses' => 'AdvsController@last']);
    Route::get('requests', ['as' => 'advs.requests', 'uses' => 'AdvsController@requests']);
    Route::get('country/{country}', ['as' => 'country', 'uses' => 'AdvsController@country']);
    Route::get('area/{area}', ['as' => 'area', 'uses' => 'AdvsController@area']);
    Route::get('category/{cat}/{cat_name}', ['as' => 'cats', 'uses' => 'AdvsController@cat']);
    Route::get('categories', ['as' => 'categories', 'uses' => 'AdvsController@cats']);
    Route::get('types/{name}', ['as' => 'types', 'uses' => 'AdvsController@types']);
    Route::get('search', ['as' => 'search', 'uses' => 'SearchController@search']);
    Route::get('searchdetails', ['as' => 'searchdetails', 'uses' => 'SearchController@getDetails']);
    Route::match(['get', 'post'], 'contactus', ['as' => 'contactus', 'uses' => 'PageController@contactus']);
    Route::resource('users', 'Profile');
    Route::group(['middleware' => 'auth'], function () {
        Route::any('select-subscription/{adv_id}', '\App\Http\Controllers\SubscriptionController@index')->name('select.subscription');
        Route::get('users/{username}/messages', ['as' => 'users.msgs', 'uses' => 'Profile@msgs', 'middleware' => 'auth']);
        Route::post('updatecontacts', ['as' => 'contacts', 'uses' => 'Profile@contacts']);
        Route::group(['middleware' => 'active'], function () {
            Route::get('user/shop/edit', ['as' => 'users.shop.edit', 'uses' => 'Profile@update']);
            Route::post('deladvs', ['as' => 'deladvs', 'uses' => 'AdvsController@remove']);
            Route::match(['get', 'post'], 'chat/{userid?}', ['as' => 'users.chat', 'uses' => 'ActionsController@chat']);
            Route::get('user/requests/{type}', ['as' => 'users.requests', 'uses' => 'Profile@requests']);
            Route::get('user/ads/{type?}', ['as' => 'users.advs', 'uses' => 'Profile@advs']);
            Route::get('user/followers/{id?}', ['as' => 'users.follow', 'uses' => 'Profile@follow']);
            Route::post('user/rates/{id}', ['as' => 'users.rates', 'uses' => 'Profile@rate2']);
            Route::get('user/rate/{id}/{type}', ['as' => 'users.rate', 'uses' => 'Profile@rate', 'middleware' => 'systems:rating']);
            Route::get('timeline', ['as' => 'users.timeline', 'uses' => 'Profile@timeline']);
            Route::get('claims/{type}', ['as' => 'users.claims', 'uses' => 'Profile@claims']);
            Route::get('user/joins', ['as' => 'users.joins', 'uses' => 'Profile@joins', 'middleware' => 'systems:joins']);
        });
        Route::get('documentation_form', ['as' => 'users.documentation_form', 'uses' => 'Profile@documentation_form', 'middleware' => 'auth']);
        Route::post('documentation_form', ['as' => 'users.documentation_form', 'uses' => 'Profile@documentation_form_post', 'middleware' => 'auth']);
    });
    Route::resource('advertise', 'AdvsController');
    Route::get('advertise/{id}/remove', 'AdvsController@remove')->name('advertise.remove');
    Route::get('advertise/{id}/republished', 'AdvsController@republished')->name('advertise.republished');
    Route::get('advertise/{id}/{slug}', ['as' => 'advertise.show', 'uses' => 'AdvsController@show']);
    Route::get('advertise-print/{id}', ['as' => 'advertise.print', 'uses' => 'AdvsController@print']);

    // commision
    Route::get('commision', ['as' => 'commision', 'uses' => 'PageController@commision']);
    Route::post('commision', ['as' => 'commision.store', 'uses' => 'PageController@commision_post']);
    Route::get('commision_respons', ['as' => 'commision.back', 'uses' => 'PageController@payment_callback']);
    // commision

    // Dexter
    //Route::get('commision_Dex', ['as' => 'commision_Dex', 'uses' => 'PageController@commision_Dex']);
    Route::post('commision_Dex', 'PageController@commision_post_Dex')->name('store_Dex');
    Route::get('commision_respons_DEx','PageController@payment_callback_DEx')->name('payment_callback_DEx');
    // Dexter

    Route::get('blacklist', ['as' => 'blacklist', 'uses' => 'IndexController@blacklist']);
    Route::group(['middleware' => 'active'], function () {
        Route::get('remove-image/{id}', ['as' => 'remove-image', 'uses' => 'AdvsController@remove_image']);
        Route::get('advertise/delete/{slug}/{id}', ['as' => 'advertise.destroy', 'uses' => 'AdvsController@destroy']);
        Route::match(['get', 'post'], 'report/{title}/{comment?}', ['as' => 'advertise.claims', 'uses' => 'AdvsController@claim', 'middleware' => 'auth']);
        // Route::match(['get','post'],'like/{id}/{type}',['as'=>'advertise.like','uses'=>'AdvsController@like','middleware'=>'auth']);
        Route::match(['get', 'post'], 'mediation', ['as' => 'advertise.median', 'uses' => 'AdvsController@median', 'middleware' => ['auth', 'systems:media']]);
        Route::match(['get', 'post'], 'actions/{id}/{slug}', ['as' => 'advertise.actions', 'uses' => 'AdvsController@actions', 'middleware' => 'auth']);
        Route::match(['get', 'post'], 'transfer', ['as' => 'transfer', 'uses' => 'PageController@transfer']);
        Route::get('favourites', ['as' => 'likes', 'uses' => 'ActionsController@likes', 'middleware' => 'auth']);
        Route::any('rates/{id}', ['as' => 'rates', 'uses' => 'ActionsController@rates']);
        Route::get('like/{id}/{user?}/{like?}', ['as' => 'like', 'uses' => 'ActionsController@like', 'middleware' => 'auth']);
        Route::post('bids', ['as' => 'bids', 'uses' => 'ActionsController@bids', 'middleware' => 'auth']);
        Route::post('comment', ['as' => 'comment', 'uses' => 'ActionsController@comment', 'middleware' => 'auth']);
        Route::get('list-bids', ['as' => 'list-bids', 'uses' => 'Profile@list_bids']);
        Route::get('notfications', ['as' => 'user.notfs', 'uses' => 'Profile@notfs']);
    });
    Route::get('page/{id}/{title}', ['as' => 'page', 'uses' => 'IndexController@page']);
    Route::get('joins', ['as' => 'joins', 'uses' => 'PageController@joins', 'middleware' => 'systems:joins']);
    Route::match(['get', 'post'], 'joins/request/{type}', ['as' => 'joins.request', 'uses' => 'PageController@getjoins', 'middleware' => 'active', 'middleware' => 'systems:joins']);
    Route::get('banking', ['as' => 'banking', 'uses' => 'PageController@banking']);
    Route::get('error/{type?}', ['as' => 'errors', 'uses' => 'PageController@error']);
    /* fm */
    Route::get('get-areas/{country_id}', ['as' => 'get-areas', 'uses' => 'ActionsController@getAreas']);
    Route::get('by-location/{country_id}/{area_id}', ['as' => 'get-areas', 'uses' => 'AdvsController@byLocation']);
});
Route::get('getDetails', [
    'as' => 'getDetails',
    'uses' => '\App\Http\Controllers\Admin\AdvsController@getDetails'
]);
use Carbon\Carbon ;
use App\Chat;
use App\Notfs;
use App\User;
Route::get("obaida" , function(){
    $advs = App\Advs::where('active' , 1)->where('end_date' , "<=" , Carbon::now())->get()->each(function($data){
        dd($data);
        $data->update([
            'active' => 0]);
    });
    return $advs;

});

Route::get('dayleftcron' , function (){

app/Advs.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use \DB;

class Advs extends Model
{

    protected $table = 'advs';
    protected $guarded = ['id'];
    protected $hidden = ['updated_at'];
    protected $appends = ['main_options', 'has_bids'];
    
    
    // public static function boot()
    // {
    //     parent::boot();

    //     static::addGlobalScope(function ($query) {
    //         if(!request()->is('admin*')) {
    //             $query->where('is_deleted',0);
    //         }
    //     });
    // }


    /**
     * 
     * @return \App\Depts
     */
    public function getdept()
    {
        return $this->belongsTo('App\Depts', 'dept');
    }

    public function getSuperDeptAttribute()
    {
        return $this->getdept->super_parent ?? $this->getdept;
    }

    public function images()
    {
        $images = $this->hasMany('App\Images', 'adv_id');
        $img = $images->get();
        if (count($img) > 0) {
            if (isset($img[0]->image)) {
                $this->setAttribute('main_image', url('/imageresize/medium/') . $img[0]->getOriginal('image'));
            } else {
                // $IMAGE_URL = DB::table('site_config')->where('id', 1)->first()->logo ?? url('site/images/placeholder.png');
                $IMAGE_URL = route('SPhone','site/images/placeholder.png');
                $this->setAttribute('main_image', URL($IMAGE_URL));
            }
        } else {
            // $IMAGE_URL = DB::table('site_config')->where('id', 1)->first()->logo ?? url('site/images/placeholder.png');
            $IMAGE_URL = route('SPhone','site/images/placeholder.png');
            $this->setAttribute('main_image', URL($IMAGE_URL));
        }
        return $images;
    }

    public function getImageAttribute()
    {
        return $this->images()->count() ? $this->images()->first()->image : url('site/images/placeholder.png');
        // return $this->images()->count() ? $this->images()->first()->image : url('site/images/logo.png');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function getarea()
    {
        return $this->belongsTo('App\Area', 'area');
    }

    public function getcountry()
    {
        return $this->belongsTo('App\Country', 'country');
    }

    public function comments()
    {
        return $this->hasMany('App\Comments', 'advs_id');
    }

    public function likes()
    {
        return $this->hasMany('App\Likes');
    }

    public function getShortAttribute()
    {
        $description = strip_tags($this->description);
        if (mb_strlen($description) > 110) {
            return mb_substr($description, 0, 110) . ' ....';
        }
        return $description;
    }

    public function likes_users()
    {
        return $this->belongsToMany('App\User', 'likes');
    }

    public function gettype()
    {
        return $this->belongsTo('App\Operations', 'type');
    }

    public function bids()
    {
        return $this->hasMany('App\Bids')->orderBy('price', 'desc')->with('user');
    }

    public function getTimeAgoAttribute()
    {
        return time_ago($this->created_at);
    }

    public function getLinkAttribute()
    {
        return route('advertise.show', [$this->id, $this->slug]);
    }

    public function getOptionsAttribute($options)
    {
        return array_filter((array) json_decode($options));
    }

    public function getAddressAttriubte()
    {
        $str = "";
        if ($country = $this->getCountry) {
            $str .= "<a href='{$country->link}'>{$country->name}</a> - ";
        }
        if ($area = $this->getArea) {
            $str .= "<a href='{$area->link}'>{$area->name}</a>";
        }
        return $str;
    }

    public function getTitlesAttribute()
    {
        $newoptions = [];
        $options = is_string($this->options) ? (array) json_decode($this->options) : (array) $this->options;
        $options = array_filter($options);
        $props = Props::whereIn('id', array_keys($options))->orderBy('title_id', 'asc')->get();
        foreach ($options as $key => $opt) {
            $newoptions['_' . $key] = $opt;
        }
        $title_id = '-1';
        $title = '#';
        $rows = [];
        foreach ($props as $prop) {
            if ($title_id != $prop->title_id) {
                $title_id = $prop->title_id;
                $title = Titles::find($prop->title_id)->name ?? '#';
            }
            $rows[$title][$prop->name] = $newoptions['_' . $prop->id] ?? '';
        }
        return $rows;
    }

    public function getMainOptionsAttribute()
    {
        $newoptions = [];
        $options = is_string($this->options) ? (array) json_decode($this->options) : (array) $this->options;
        $options = array_filter($options);
        $props = Props::whereIn('id', array_keys($options))->where('main', 1)->take(3)->get();
        foreach ($options as $key => $opt) {
            $newoptions['_' . $key] = $opt;
        }
        $rows = [];
        foreach ($props as $prop) {
            $rows[$prop->icon] = $newoptions['_' . $prop->id] ?? '';
        }
        if (empty($rows)) {
            if ($this->getdept) {
                $props = Props::where('dept_id', $this->getdept->super_id)->where('main', 1)->get();
                foreach ($props as $prop) {
                    $rows[$prop->icon] = '';
                }
            }
        }
        return $rows;
    }


    public function getSimilarsAttribute()
    {
        return Advs::where('dept', $this->dept)->where('id', '!=', $this->id)->latest()->take(3)->get();
    }

    public function getTreeAttribute()
    {
        $dept = $this->getdept;
        $tree = "";
        if ($parent = $dept->parent) {
            $tree .= $this->hasTree($parent);
        }
        $tree .= "<li><a href='{$dept->link}' class='fixall'>{$dept->name}</a></li>";
        $tree .= "<li><a href='#' class='fixall'>{$this->title}</a></li>";
        return html_entity_decode($tree);
    }
    
    public function hasTree($val) {
        $return = '';
        if(!is_null($val->parent)) {
            $p = $val->parent;
            $return .= $this->hasTree($p);
        }
        $return .= "<li><a href='{$val->link}' class='fixall'>{$val->name}</a></li>";
        return $return;
    }

    public static function scopeGetByDistance($query, $lat, $lng, $distance)
    {
        $results = DB::select(DB::raw('SELECT id, ( 3959 * acos( cos( radians(' . $lat . ') ) * cos( radians( lat ) ) * cos( radians( lng ) - radians(' . $lng . ') ) + sin( radians(' . $lat . ') ) * sin( radians(lat) ) ) ) AS distance FROM advs HAVING distance < ' . $distance . ' ORDER BY distance'));
        $ids = [];
        if (!empty($results)) {
            foreach ($results as $q) {
                array_push($ids, $q->id);
            }
        }
        return $query->whereIn('id', $ids);
    }

    public function getHasBidsAttribute()
    {
        $dept = Depts::find($this->getOriginal('dept'));
        return $dept && $dept->super_parent->home ? true : false;
    }
    
    public function catgeories() {
        return $this->belongsToMany(Depts::class, 'advs_depts_pivot', 'adv_id', 'dept_id');
    }
    public function subscription(){
        return $this->hasOne('App\Subscription' , 'id' , 'subscription_id' );
    }
}

resources/views/admin/advs/claims.blade.php
@extends('admin.index')
@section('title') أخر الاعلانات المبلغ عنها @stop
@section('page')

	<!-- Main content -->
		<div class="content-wrapper">

			<!-- Page header -->
			<div class="page-header">
				<div class="page-header-content">
					<div class="page-title">
						<h4><i class="icon-arrow-right6 position-right"></i> <span class="text-semibold">اعدادات التطبيق</span> - أخر الاعلانات المبلغ عنها</h4>
					</div>

				</div>

				<div class="breadcrumb-line">
					<ul class="breadcrumb">
						<li><a><i class="icon-home2 position-left"></i> اعدادات التطبيق</a></li>
						<li><a href="{{route('admin.advs.index')}}?type=report">أخر الاعلانات المبلغ عنها</a></li>
					</ul>
				</div>
			</div>
			<!-- /page header -->

			@if(Session::has('true'))
			<div class="alert alert-success">تم الاضافة بنجاح</div>
			@endif
			<!-- Content area -->
			<div class="content">
				<!-- Basic initialization -->
				<div class="panel panel-flat table-responsive">
					<table class="table datatable-key-basic">
						<thead>
							<tr>
								<th>#</th>
								<th>الشاكى</th>
								<th>نص الشكوى</th>
								<th>التاريخ</th>
								<th>الاعلان</th>
								
								
							</tr>
						</thead>
						<tbody>
						    
							<?php $i=1; ?>
							@foreach($claims as $info)
								<tr>
									<td>{{ $i++ }}</td>
									<td><a href="{{route('admin.users.edit',$info->user->id)}}">{{ $info->user->username }}</a></td>
									<td>{{ $info->text }}</td>
									<td>{{ date('Y-m-d',strtotime($info->created_at)) }}</td>
									<td><a href="{{ route('admin.advs.edit',$info->advs->id) }}">{{ $info->advs->title }} </a></td>
									
								</tr>
							@endforeach
						</tbody>
					</table>
				</div>
				<!-- /basic initialization -->
			</div>
			<!-- /content area -->

		</div>
		<!-- /main content -->
@stop

resources/views/admin/advs/edit.blade.php
@extends('admin.index')
@section('title') تعديل إعلان @stop
@section('page')
<!-- Main content -->
<div class="content-wrapper">
	<!-- Page header -->
	<div class="page-header">
		<div class="page-header-content">
			<div class="page-title">
				<h4><i class="icon-arrow-right6 position-right"></i> <span class="text-semibold">الإعلانات</span> - تعديل
					إعلان</h4>
			</div>
		</div>
		<div class="breadcrumb-line">
			<ul class="breadcrumb">
				<li><a href="{{route('admin.advs.index')}}">الإعلانات</a></li>
				<li>تعديل إعلان</li>
			</ul>
		</div>
	</div>
	<!-- /page header -->
	<!-- Content area -->
	<div class="content">
		<!-- Input group addons -->
		<div class="panel panel-flat table-responsive">
			<div class="panel-body">
				<form action="{{ route('admin.advs.update',$info->id) }}" class="form-horizontal" method="post"
					enctype="multipart/form-data" files>
					@if(Session::has('error'))
					<div class="alert alert-warning">{{Session::get('error')}}</div>
					@elseif(Session::has('true'))
					<div class="alert alert-success">تم التعديل بنجاح</div>
					@endif
					<fieldset class="content-group">
						<legend class="text-bold">إضافة إعلان</legend>
						<div class="form-group">
							<label class="control-label col-lg-2">القسم</label>
							<div class="col-lg-10">
								<div class="input-group">

									<select required class="form-control selectpicker advs_dept_id" data-live-search="true"
										name="dept" id="advs_dept_id" data-action="{{route('getDetails')}}" title="اختر القسم">
										@foreach($depts as $dp)
										<option {{ $info->super_dept->id == $dp->id ? 'selected' : '' }} @if($info->dept==$dp->id)
											selected @endif value="{{$dp->id}}">{{$dp->name}}
										</option>
										@endforeach
									</select>
								</div>
							</div>
						</div>
						<div class="advs_details">
							@if(isset($advs_details))
							@foreach($advs_details as $adt)
							@foreach($adt as $key=>$ad)
							@if($key != 'others' && $key!= 'type')
							@if($adt['type']=='input')
							<div class="form-group">
								<label class="control-label col-lg-2">{{$key}}</label>
								<div class="col-lg-10">
									<div class="input-group">

										<input required value="{{$ad}}" type="text" name="{{$key}}" class="form-control">
									</div>
								</div>
							</div>
							@else
							<div class="form-group">
								<label class="control-label col-lg-2">{{$key}}</label>
								<div class="col-lg-10">
									<div class="input-group">

										<select required class="form-control proptype" name="{{$key}}">
											@foreach($adt['others'] as $ot)
											<option @if($ot->name==$ad) selected @endif value="{{$ot->name}}">
												{{ $ot->name }}
											</option>
											@endforeach
										</select>
									</div>
								</div>
							</div>
							@endif
							@endif
							@endforeach
							@endforeach
							@endif
						</div>

						{{ method_field('PUT') }}
						<div class="advs_proptypes">
							@if(isset($advs_proptypes))
							@foreach($advs_proptypes as $adt)
							@foreach($adt as $key=>$ad)
							@if($key != 'others' && $key!= 'type')
							@if($adt['type']=='input')
							<div class="form-group">
								<label class="control-label col-lg-2">{{$key}}</label>
								<div class="col-lg-10">
									<div class="input-group">

										<input required value="{{$ad}}" type="text" name="{{$key}}" class="form-control">
									</div>
								</div>
							</div>
							@else
							<div class="form-group">
								<label class="control-label col-lg-2">{{$key}}</label>
								<div class="col-lg-10">
									<div class="input-group">

										<select required class="form-control" name="{{$key}}">
											@foreach($adt['others'] as $ot)
											<option @if($ot->name==$ad) selected @endif value="{{$ot->name}}">
												{{ $ot->name }}
											</option>
											@endforeach
										</select>
									</div>
								</div>
							</div>
							@endif
							@endif
							@endforeach
							@endforeach
							@endif
						</div>
						<div class="form-group">

							<label class="control-label col-lg-2">حالة المنتج</label>

							<div class="col-lg-10">

								<div class="input-group">



									<select required class="form-control" name="status">
										<option>جديد</option>
										<option {{ $info->status=="مستعمل" ? 'selected' : '' }}>مستعمل</option>
									</select>

								</div>

							</div>

						</div>

						<div class="type_details">
							@if(isset($type_details))
							@foreach($type_details as $adt)
							@foreach($adt as $key=>$ad)
							<div class="form-group">
								<label class="control-label col-lg-2">{{ $type_keys[$key] }}</label>
								<div class="col-lg-10">
									<div class="input-group">

										<input value="{{$ad}}" type="text" name="{{$key}}" class="form-control">
									</div>
								</div>
							</div>
							@endforeach
							@endforeach
							@endif
						</div>
						<div class="form-group">
							<label class="control-label col-lg-2">عنوان الإعلان</label>
							<div class="col-lg-10">
								<div class="input-group">

									<input required value="{{$info->title}}" type="text" name="title" class="form-control">
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-lg-2">المواصفات</label>
							<div class="col-lg-10">
								<div class="input-group">

									<textarea rows="5" required class="form-control" name="description">{{ $info->description }}
										</textarea>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-lg-2">الكلمات الدالة</label>
							<div class="col-lg-10">
								<div class="input-group">

									<input name="keywords" value="{{$info->keywords}}" id="tags" class="form-control">
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-lg-2">اضافة صور أخرى</label>
							<div class="col-lg-10">
								<div class="input-group">
									<span class="input-group-addon fa"></span>
									<input type="file" id="multi-uploadfile" multiple class="form-control" name="images[]">
								</div>
								<div class="images_div">
									@foreach($info->images as $image)
									<div class="col-sm-2">
										<div>
											<a class="btn btn-danger fa fa-remove" data-table='images'
												data-id='{{$image->id}}'></a>
											<img src="{{ url($image->image) }}" alt="">
										</div>
									</div>
									@endforeach
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-lg-2">المنطقة</label>
							<div class="col-lg-10">
								<div class="col-sm-6">
									<div class="input-group">

										<select required data-live-search="true" class="form-control" name="country" id="country">
											@foreach($country as $ct)
											<option @if($info->country==$ct->id) selected @endif value="{{$ct->id}}">{{$ct->name}}
											</option>
											@endforeach
										</select>
									</div>
								</div>
								<div class="col-sm-6">
									<div class="input-group area_content">

										<select required class="form-control" name="area" id="area">
											@foreach($area as $ar)
											<option value="{{$ar->id}}" @if($ar->id==$info->area) selected @endif > {{$ar->name}}
											</option>
											@endforeach
										</select>
									</div>
								</div>
							</div>
						</div>
						<script type="text/javascript">
						</script>
						{{ csrf_field() }}
					</fieldset>
					<div class="text-right">
						<button type="submit" class="btn btn-primary">حفظ<i
								class="icon-arrow-left13 position-right"></i></button>
					</div>
				</form>
			</div>
		</div>
		<!-- /input group addons -->
	</div>
	<!-- /content area -->
</div>
<!-- /content wrapper -->
@push('scripts')
<script>
	get_dept_props("{{ $info->super_dept->id }}" , "{{ $info->id }}")
</script>
@endpush
@stop